config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  post 'login', to: 'sessions#create'

  resources :posts, only: [:new, :create, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates :heading, presence: true
  validates :content, presence: true

def author
    User.find(!self.user_id)
end 
end

app/models/user.rb
class User < ApplicationRecord
  before_create :create_remember_token
  has_many :posts

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, uniqueness: true, :length => { :in => 3..20 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX}
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  private 
  def create_remember_token
    s = SecureRandom.urlsafe_base64
    self.remember_token = Digest::SHA1.hexdigest s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      @post.user_id = current_user.id
      flash.now[:success] = 'Post was successfully created.'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all.sort{|a,b| b.created_at <=> a.created_at }
  end

  private

  def post_params
    params.require(:post).permit(:heading, :content)
  end

  def logged_in_user
    unless logged_in?
    flash[:notice] = 'Kindly login.'
    redirect_to login_path 
  end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      remember user
      flash.now[:sucess] = 'Login successfull'
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # login the user and redirect to posts page
      log_in @user
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def author
    User.find(self.user_id)
end 
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def remember(user)
    user.create_remember_token
   cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    @current_user = user
   end
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id] != nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def log_out
    session.delete(:user_id)
     @current_user = nil
   end
  
  def generate_token
    s = SecureRandom.urlsafe_base64
    Digest::SHA1.hexdigest s
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_top.html.erb
<div class="w-full flex justify-between items-center px-12 py-2 border-b">
  <a href="<%= root_url %>" class="w-1/4 logo flex items-center">

    <h1 class="text-lg">Members Only</h1>
  </a>
  <ul class="flex">
    <% if logged_in? %>
    <li class="mx-2"><%= link_to 'New Post',    new_post_path, :class => 'text-red-800 font-medium hover:underline' %></li>
    <li class="mx-2"><%= link_to 'Posts',    posts_path, :class => 'text-red-800 font-medium hover:underline' %></li>
    <li class="mx-2"><%= link_to 'Logout',    logout_path, method: :delete, :class => 'text-red-800 font-medium hover:underline' %></li>
    <%else%>
    <li class="mx-2"><%= link_to 'Login',    login_path, :class => 'text-red-800 font-medium hover:underline' %></li>
    <li class="mx-2"><%= link_to 'Register', register_path, :class => 'text-red-800 font-medium hover:underline' %></li>
    <%end%>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <div class="h-screen flex flex-col justify-between">
      <%= render 'layouts/top' %>
      <% if not flash.empty? %>
      <div class="mx-auto w-3/4 my-4">
        <h3 class="w-full text-center rounded py-2 px-4 bg-blue-300 text-blue-900"><%= flash[:notice] %></h3>
      </div>
      <%end%>
      <div class="w-1/2 container mx-auto my-4">
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>

app/views/posts/index.html.erb
<h2>All Posts</h2>
<% @posts.each do |post| %>
<div class="border rounded p-2 my-2">
  <h1 class="title text-lg px-4 py-2 font-medium">
    <%= post.heading %>
    <span class="text-gray-300">#<%= post.id %></span>
  </h1>
  <p class="text-base tracking-normal"><%= post.content %></p>
  <p class="text-gray-400">posted in <%= distance_of_time_in_words(post.created_at, DateTime.now) %>
    <% if logged_in? %>
      by <%= post.author.name.titleize %>
    <%end%>
  </p>
</div>
<%end%>

app/views/posts/new.html.erb
<div class="flex items-center mx-4 mb-12">
  <h1 class="text-xl">New Post</h1>
</div>
<%= form_for(@post, url: posts_path) do |f| %>
<% if @post.errors.any? %>
<ul class="errors list-disc">
  <% @post.errors.full_messages.each do |error| %>
  <li class="text-red-500 mx-4"><%= error %></li>
  <%end%>
</ul>
<%end%>
<div class="flex flex-col outline">
  <div class="flex my-2 mx-4">
    <%= f.label :heading, class: 'w-1/6' %>
    <%= f.text_field :heading, class: 'w-1/2 border rounded' %>
  </div>
  
  <div class="flex my-2 mx-4">
    <%= f.label :content, class: 'w-1/6' %>
    <%= f.text_area :content, class: 'w-1/2 border rounded' %>
  </div>

  <div class="flex my-2 mx-4">
    <%= f.submit "create post", :class => 'px-4 py-1 cursor-pointer rounded bg-blue-500 text-white'  %>
  </div>
</div>
<%end%>

app/views/posts/show.html.erb
<%= @post.title %>

app/views/users/new.html.erb
<div class="flex items-center mx-4 mb-12">
    <h1 class="text-xl">Members Only | Please Register</h1>
</div>
<%= form_for(@user, url: register_path) do |f| %>
  <% if @user.errors.any? %>
  <ul class="errors list-disc">
    <% @user.errors.full_messages.each do |error| %>
    <li class="text-red-500 mx-4"><%= error %></li>
    <%end%>
  </ul>
  <%end%>
  <div class="flex flex-col outline">
    <div class="flex my-2 mx-4">
      <%= f.label :name, class: 'w-1/6' %>
      <%= f.text_field :name, class: 'w-1/2 border rounded' %>
    </div>
    
    <div class="flex my-2 mx-4">
      <%= f.label :email, class: 'w-1/6' %>
      <%= f.email_field :email, class: 'w-1/2 border rounded' %>
    </div>

    <div class="flex my-2 mx-4">
      <%= f.label :password, class: 'w-1/6' %>
      <%= f.password_field :password, class: 'w-1/2 border rounded' %>
    </div>

    <div class="flex my-2 mx-4">
      <%= f.label :password_confirmation, 'Confirmation',  class: 'w-1/6' %>
      <%= f.password_field :password_confirmation, class: 'w-1/2 border rounded' %>
    </div>
    <div class="flex my-2 mx-4">
      <%= f.submit "create user", :class => 'px-4 py-1 cursor-pointer rounded bg-blue-500 text-white'  %>
    </div>
  </div>
<%end%>

app/views/users/show.html.erb
<div class="container posts-new">
  <div class="row">
    <h1>MY PROFILE</h1>
    <div class="col-lg-6">
      <img class="img-fluid rounded mb-3 mb-md-0" src="https://picsum.photos/150/150" alt="">
    </div>
    <div class="col-lg-6">
      <h1>Hello!, <%= @user.username %></h1>
      <h3>You have: <%= @user.posts.count %> Scams</h3>
    </div>
  </div>
</div>